
var purchaseOrderProcessResult = await PurchaseOrderProcessor.ProcessPurchaseOrders();

PurchaseOrderReultPrinter.PrintValidResults(purchaseOrderProcessResult.ValidPurchaseOrders);
PurchaseOrderReultPrinter.PrintInValidResults(purchaseOrderProcessResult.InValidPurchaseOrders);
PurchaseOrderReultPrinter.PrintUnprocessableResults(purchaseOrderProcessResult.UnprocessablePurchaseOrders);

await DbService.InsertPuchaseOrders(purchaseOrderProcessResult.ValidPurchaseOrders);